In [2]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException

from bs4 import BeautifulSoup
import requests

import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

### Scraping For Jersey City, NJ

In [19]:
#opening the rentberry Austin,Tx page on automated chrome browser
driver = webdriver.Chrome()
driver.get('https://rentberry.com/apartments/s/jersey-city-nj')
time.sleep(2)

In [4]:
rent_URL = []
rent_Price = []

In [5]:
# to scrap URL of 66 pages
start = 0
end = 40

for page in range(start,end):
    url_tags= driver.find_elements(By.XPATH,'//a[@class="property-card-bottom-address__text link-ghost font-xs one-line-string"]')
    price = driver.find_elements(By.XPATH,'//rb-property-card-bottom[@class="property-card__bottom"]/div/div/rb-property-card-price/div/p')
   
    for _ in range(100):
        driver.execute_script("window.scrollBy(0,1000)")
        
    for t in url_tags:
        rent_URL.append(t.get_attribute('href'))
    for a in price:
        rent_Price.append(a.text)
        
    next_page = driver.find_element(By.XPATH,'//span[@class="pagination-arrow-next"]')
    next_page.click()
 
    time.sleep(5)

In [7]:
print(len(rent_URL),len(rent_Price))

880 880

In [6]:
rent_Pets = []
rent_Area = []
rent_Address = []
rent_Deposit = []
rent_Beds = []
rent_Bathroom = []
rent_Washer_Dryer =[]
rent_AC = []
rent_Parking=[]
rent_Fireplace=[]
rent_Dishwasher=[]
rent_Floors=[]
rent_Roofdeck=[]
rent_Storage=[]

In [20]:
for t in rent_URL[791:]:
    driver.get(t)
    time.sleep(5)
    
    
    try:
        add = driver.find_element(By.XPATH,'/html/body/rb-core/div/rb-property/div/rb-property-main-info/section/div/div/rb-property-data/div/h4/span/span')
        rent_Address.append(add.text)
    except NoSuchElementException:
        rent_Address.append('np.nan')
        
    try:
        bed = driver.find_element(By.XPATH,"//*[contains(@class,'bedrooms')]")
        rent_Beds.append(bed.text)
    except NoSuchElementException:
        rent_Beds.append('np.nan') 
        
    try:
        bath = driver.find_element(By.XPATH,"//*[contains(@class,'bathrooms')]")
        rent_Bathroom.append(bath.text)
    except NoSuchElementException:
        rent_Bathroom.append('np.nan') 
        
    try:
        sqft = driver.find_element(By.XPATH,"//*[contains(@class,'space')]")
        rent_Area.append(sqft.text)
    except NoSuchElementException:
        rent_Area.append('np.nan')
        
    try:
        pets = driver.find_element(By.XPATH,"//*[contains(@class,'dog-icon facilities-param-icon')]" or "//*[contains(@class,'cat-icon facilities-param-icon')]")
        rent_Pets.append('Yes')
    except NoSuchElementException:
        rent_Pets.append('No')
        
    try:
        adv = driver.find_element(By.XPATH,'/html/body/rb-core/div/rb-property/div/div[2]/div/rb-apply-block/div/div/rb-button-square/button/span/span[2]/span[1]')
        rent_Deposit.append(adv.text.replace("Apply for $",''))
    except NoSuchElementException:
        rent_Deposit.append('np.nan')
        
    try:
        was = driver.find_element(By.XPATH, "//*[contains(@class,'icon washerUnit')]")
        rent_Washer_Dryer.append('Yes')
    except NoSuchElementException:
        rent_Washer_Dryer.append('No')   
        
    try:
        ac = driver.find_element(By.XPATH,"//*[contains(@class,'airConditioning icon')]")
        rent_AC.append('Yes')
    except NoSuchElementException:
        rent_AC.append('No')
       
    try:
        park = driver.find_element(By.XPATH,"//*[contains(@class,'icon parking')]")
        rent_Parking.append('Yes')
    except NoSuchElementException:
        rent_Parking.append('No') 

    try:
        dish = driver.find_element(By.XPATH,"//*[contains(@class,'dishwasher icon')]")
        rent_Dishwasher.append('Yes')
    except NoSuchElementException: 
        rent_Dishwasher.append('No')
    try:
        hard = driver.find_element(By.XPATH,"//*[contains(@class,'hardwoodFloors icon')]")
        rent_Floors.append('Yes')
    except NoSuchElementException:
        rent_Floors.append('No')
        
    try:
        roof = driver.find_element(By.XPATH,"//*[contains(@class,'icon roofDeck')]")
        rent_Roofdeck.append('Yes')  
    except NoSuchElementException:
        rent_Roofdeck.append('No')
        
    try:
        store = driver.find_element(By.XPATH, "//*[contains(@class,'icon storage')]")
        rent_Storage.append('Yes')
    except NoSuchElementException: 
        rent_Storage.append('No')
                    
    try:
        fire = driver.find_element(By.XPATH, "//*[contains(@class,'fireplace icon')]")
        rent_Fireplace.append('Yes')
    except NoSuchElementException:  
        rent_Fireplace.append('No')

In [21]:
print(len(rent_URL), len(rent_Price),len(rent_Address),len(rent_Bathroom),len(rent_Beds),len(rent_Area),len(rent_Pets),len(rent_Deposit),len(rent_AC),len(rent_Washer_Dryer),len(rent_Parking),len(rent_Dishwasher),len(rent_Floors),len(rent_Roofdeck),len(rent_Storage), len(rent_Fireplace))

880 880 880 880 880 880 880 880 880 880 880 880 880 880 880 880

In [22]:
jersey = pd.DataFrame({'URL':rent_URL,'Address':rent_Address,'Rental Price':rent_Price,'Deposit':rent_Deposit,
                      'Bathroom':rent_Bathroom,'Bedroom':rent_Beds,'Rental Area':rent_Area,'Pets':rent_Pets,
                      'AC':rent_AC,'Washer_Dryer':rent_Washer_Dryer,'Parking':rent_Parking,'Dishwasher':rent_Dishwasher,
                      'Floors':rent_Floors,'Roofdeck':rent_Roofdeck,'Storage':rent_Storage,'Fireplace':rent_Fireplace})
jersey

,URL,Address,Rental Price,Deposit,Bathroom,Bedroom,Rental Area,Pets,AC,Washer_Dryer,Parking,Dishwasher,Floors,Roofdeck,Storage,Fireplace
0,https://rentberry.com/houses/116553594-two-br-...,"403 Park Avenue, Weehawken, NJ 07086, USA","$2,350","2,350",1.5,2,"1,008",No,No,No,No,No,No,No,No,No
1,https://rentberry.com/houses/114786662-one-br-...,"75 Irving Street, Jersey City, NJ 07307, USA","$2,400","2,400",1,1,680,No,No,No,No,No,No,No,No,No
2,https://rentberry.com/houses/115076995-two-br-...,"10 Bennett Street, Jersey City, NJ 07304, USA","$3,200","3,200",2,2,"1,506",No,No,No,No,No,No,No,No,No
3,https://rentberry.com/houses/116893091-two-br-...,"120 Sherman Avenue, Jersey City, NJ 07307, USA","$3,850","3,850",2,2,"1,322",No,No,No,No,No,No,No,No,No
4,https://rentberry.com/apartments/116437600-two...,"197 Marin Blvd, Unit 0419-2","$4,520","4,520",2,2,979,Yes,No,No,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,https://rentberry.com/apartments/96394664-two-...,"Hoboken, NJ, 07030","$7,500",np.nan,1,2,np.nan,No,Yes,No,No,No,No,No,No,No
876,https://rentberry.com/apartments/84776662-one-...,"Jersey City, NJ, US","$1,800",np.nan,1,1,np.nan,No,No,No,No,No,No,No,No,No
877,https://rentberry.com/apartments/97859155-four...,"Hoboken, NJ, 07030","$8,250",np.nan,1,4,800,No,Yes,No,No,Yes,No,No,No,No
878,https://rentberry.com/apartments/90460765-six-...,"33 East 51st Street, Bayonne, NJ 07002, USA","$4,000","4,000",3,6,"2,000",No,Yes,No,Yes,Yes,No,No,No,No
879,https://rentberry.com/apartments/90086931-one-...,"294 Coles Street, Jersey City, NJ 07302, USA","$1,950","1,950",1,1,np.nan,No,Yes,No,No,Yes,No,No,No,No

In [23]:
import numpy as np

In [24]:
jersey = jersey.replace("np.nan", np.nan)

In [25]:
jersey.isnull().sum()

URL               0
Address          29
Rental Price      0
Deposit         128
Bathroom         33
Bedroom          29
Rental Area     384
Pets              0
AC                0
Washer_Dryer      0
Parking           0
Dishwasher        0
Floors            0
Roofdeck          0
Storage           0
Fireplace         0
dtype: int64

In [26]:
# Cleaning dataframe , drop nan from area since its target variable
jersey = jersey[~jersey['Rental Area'].isna()]
jersey

,URL,Address,Rental Price,Deposit,Bathroom,Bedroom,Rental Area,Pets,AC,Washer_Dryer,Parking,Dishwasher,Floors,Roofdeck,Storage,Fireplace
0,https://rentberry.com/houses/116553594-two-br-...,"403 Park Avenue, Weehawken, NJ 07086, USA","$2,350","2,350",1.5,2,"1,008",No,No,No,No,No,No,No,No,No
1,https://rentberry.com/houses/114786662-one-br-...,"75 Irving Street, Jersey City, NJ 07307, USA","$2,400","2,400",1,1,680,No,No,No,No,No,No,No,No,No
2,https://rentberry.com/houses/115076995-two-br-...,"10 Bennett Street, Jersey City, NJ 07304, USA","$3,200","3,200",2,2,"1,506",No,No,No,No,No,No,No,No,No
3,https://rentberry.com/houses/116893091-two-br-...,"120 Sherman Avenue, Jersey City, NJ 07307, USA","$3,850","3,850",2,2,"1,322",No,No,No,No,No,No,No,No,No
4,https://rentberry.com/apartments/116437600-two...,"197 Marin Blvd, Unit 0419-2","$4,520","4,520",2,2,979,Yes,No,No,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,https://rentberry.com/apartments/96210281-two-...,"Hoboken, NJ, 07030","$2,610",NaN,1,2,800,Yes,Yes,No,Yes,Yes,No,No,No,No
871,https://rentberry.com/houses/108004470-four-br...,"Jersey City, NJ","$23,010",NaN,4,4,"2,080",Yes,Yes,No,Yes,Yes,No,No,No,No
874,https://rentberry.com/apartments/115295823-thr...,"Bayonne, NJ, 07002","$11,970",NaN,2,3,"1,250",No,Yes,No,Yes,Yes,No,No,No,No
877,https://rentberry.com/apartments/97859155-four...,"Hoboken, NJ, 07030","$8,250",NaN,1,4,800,No,Yes,No,No,Yes,No,No,No,No
878,https://rentberry.com/apartments/90460765-six-...,"33 East 51st Street, Bayonne, NJ 07002, USA","$4,000","4,000",3,6,"2,000",No,Yes,No,Yes,Yes,No,No,No,No

In [28]:
jersey.insert(0, 'Sl_No', range(1, 1 + jersey.shape[0]))
jersey.insert(3, 'City', "Jersey City")
jersey.insert(4, 'State', "NJ")
jersey.insert(5, 'Country', "USA")

jersey

,Sl_No,URL,Address,City,State,Country,Rental Price,Deposit,Bathroom,Bedroom,Rental Area,Pets,AC,Washer_Dryer,Parking,Dishwasher,Floors,Roofdeck,Storage,Fireplace
0,1,https://rentberry.com/houses/116553594-two-br-...,"403 Park Avenue, Weehawken, NJ 07086, USA",Jersey City,NJ,USA,"$2,350","2,350",1.5,2,"1,008",No,No,No,No,No,No,No,No,No
1,2,https://rentberry.com/houses/114786662-one-br-...,"75 Irving Street, Jersey City, NJ 07307, USA",Jersey City,NJ,USA,"$2,400","2,400",1,1,680,No,No,No,No,No,No,No,No,No
2,3,https://rentberry.com/houses/115076995-two-br-...,"10 Bennett Street, Jersey City, NJ 07304, USA",Jersey City,NJ,USA,"$3,200","3,200",2,2,"1,506",No,No,No,No,No,No,No,No,No
3,4,https://rentberry.com/houses/116893091-two-br-...,"120 Sherman Avenue, Jersey City, NJ 07307, USA",Jersey City,NJ,USA,"$3,850","3,850",2,2,"1,322",No,No,No,No,No,No,No,No,No
4,5,https://rentberry.com/apartments/116437600-two...,"197 Marin Blvd, Unit 0419-2",Jersey City,NJ,USA,"$4,520","4,520",2,2,979,Yes,No,No,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,492,https://rentberry.com/apartments/96210281-two-...,"Hoboken, NJ, 07030",Jersey City,NJ,USA,"$2,610",NaN,1,2,800,Yes,Yes,No,Yes,Yes,No,No,No,No
871,493,https://rentberry.com/houses/108004470-four-br...,"Jersey City, NJ",Jersey City,NJ,USA,"$23,010",NaN,4,4,"2,080",Yes,Yes,No,Yes,Yes,No,No,No,No
874,494,https://rentberry.com/apartments/115295823-thr...,"Bayonne, NJ, 07002",Jersey City,NJ,USA,"$11,970",NaN,2,3,"1,250",No,Yes,No,Yes,Yes,No,No,No,No
877,495,https://rentberry.com/apartments/97859155-four...,"Hoboken, NJ, 07030",Jersey City,NJ,USA,"$8,250",NaN,1,4,800,No,Yes,No,No,Yes,No,No,No,No
878,496,https://rentberry.com/apartments/90460765-six-...,"33 East 51st Street, Bayonne, NJ 07002, USA",Jersey City,NJ,USA,"$4,000","4,000",3,6,"2,000",No,Yes,No,Yes,Yes,No,No,No,No

### Creating Tables

### Table1

In [29]:
Sl_no = jersey['Sl_No'].tolist()
Address = jersey['Address'].tolist()
city = jersey['City'].tolist()
state = jersey['State'].tolist()
country = jersey['Country'].tolist()
price = jersey['Rental Price'].tolist()
Deposit = jersey['Deposit'].tolist()

jersey_Table1 =pd.DataFrame({
    'Sl_No':Sl_no,
    'Address': Address,
    'City': city,
    'State': state,
    'Country' : country,
    'Price': price,
    'Deposit': Deposit
})
jersey_Table1


jersey_Table1.to_csv('jersey_Table1.csv', index=False)

### Table 2

In [30]:
Sl_no = jersey['Sl_No'].tolist()
Beds = jersey['Bedroom'].tolist()
Baths = jersey['Bathroom'].tolist()
R_area = jersey['Rental Area'].tolist()
pets = jersey['Pets'].tolist()

jersey_Table2 =pd.DataFrame({
    'Sl_No':Sl_no,
    'Bedrooms': Beds,
    'Bathrooms': Baths,
    'Area' : R_area,
    'Pets Allowed': pets,
})
jersey_Table2


jersey_Table2.to_csv('jersey_Table2.csv', index=False)

### Table 3

In [31]:
Sl_no = jersey['Sl_No'].tolist()
AC = jersey['AC'].tolist()
washer = jersey['Washer_Dryer'].tolist()
Parking = jersey['Parking'].tolist()
Dishwasher = jersey['Dishwasher'].tolist()
floor = jersey['Floors'].tolist()
roof = jersey['Roofdeck'].tolist()
storage = jersey['Storage'].tolist()
fireplace = jersey['Fireplace'].tolist()


jersey_Table3 =pd.DataFrame({
    'Sl_No':Sl_no,
    'Washer/Dryer': washer,
    'AC': AC,
    'Parking' : Parking,
    'Fireplace': fireplace,
    'Dishwasher': Dishwasher,
    'Hardwood floors': floor,
    'Roofdeck': roof,
    'storage': storage
})

jersey_Table3


jersey_Table3.to_csv('jersey_Table3.csv', index=False)

In [32]:
jersey.to_csv('jersey.csv', index = False)